# Internal implementation registry for the 70 scientific blocks.
.mixedflow_blocks <- list(
  "1" = list(module = "Design audit", function_name = "mixed_design_audit", status = "implemented"),
  "2" = list(module = "Experimental hierarchy", function_name = "mixed_hierarchy", status = "implemented"),
  "3" = list(module = "Balance and cell support", function_name = "mixed_balance", status = "implemented"),
  "4" = list(module = "Pseudoreplication screen", function_name = "mixed_pseudorep", status = "implemented"),
  "5" = list(module = "Legacy split-plot fit", function_name = "fit_legacy_splitplot", status = "implemented"),
  "6" = list(module = "Expected mean squares", function_name = "splitplot_ems", status = "implemented"),
  "7" = list(module = "Legacy ANOVA extraction", function_name = "splitplot_anova", status = "implemented"),
  "8" = list(module = "Legacy-to-mixed comparison", function_name = "compare_legacy_mixed", status = "implemented"),
  "9" = list(module = "Split-split plot", function_name = "fit_legacy_splitsplit", status = "implemented"),
  "10" = list(module = "Strip-plot", function_name = "fit_legacy_stripplot", status = "implemented"),
  "11" = list(module = "General mixed fit", function_name = "mixed_fit", status = "implemented"),
  "12" = list(module = "Random intercepts", function_name = "mixed_random_intercepts", status = "implemented"),
  "13" = list(module = "Random slopes", function_name = "mixed_random_slopes", status = "implemented"),
  "14" = list(module = "Nested effects", function_name = "mixed_nested", status = "implemented"),
  "15" = list(module = "Crossed effects", function_name = "mixed_crossed", status = "implemented"),
  "16" = list(module = "BLUP extraction", function_name = "mixed_blup", status = "implemented"),
  "17" = list(module = "General GLMM", function_name = "mixed_glmm", status = "implemented"),
  "18" = list(module = "Binomial GLMM", function_name = "mixed_binomial", status = "implemented"),
  "19" = list(module = "Count GLMM", function_name = "mixed_count", status = "implemented"),
  "20" = list(module = "Beta mixed model", function_name = "mixed_beta", status = "implemented"),
  "21" = list(module = "Zero-inflated mixed model", function_name = "mixed_zero_inflated", status = "implemented"),
  "22" = list(module = "Covariance specification", function_name = "mixed_covariance", status = "implemented"),
  "23" = list(module = "Residual heterogeneity", function_name = "mixed_heterogeneity", status = "implemented"),
  "24" = list(module = "Discrete AR1", function_name = "mixed_ar1", status = "implemented"),
  "25" = list(module = "Continuous AR1", function_name = "mixed_car1", status = "implemented"),
  "26" = list(module = "Toeplitz/structured covariance", function_name = "mixed_toeplitz", status = "implemented"),
  "27" = list(module = "Covariance-model comparison", function_name = "mixed_covariance_compare", status = "implemented"),
  "28" = list(module = "Spatiotemporal mixed model", function_name = "mixed_spatiotemporal", status = "implemented"),
  "29" = list(module = "Spatial covariance model", function_name = "mixed_spatial_covariance", status = "implemented"),
  "30" = list(module = "Temporal prediction grid", function_name = "mixed_temporal_grid", status = "implemented"),
  "31" = list(module = "Covariance visualization", function_name = "mixed_covariance_plot", status = "implemented"),
  "32" = list(module = "Robust LMM", function_name = "mixed_robust", status = "implemented"),
  "33" = list(module = "Robust influence screen", function_name = "mixed_robust_influence", status = "implemented"),
  "34" = list(module = "Classical-robust comparison", function_name = "mixed_compare_robust", status = "implemented"),
  "35" = list(module = "Contamination sensitivity", function_name = "mixed_contamination", status = "implemented"),
  "36" = list(module = "Cluster-robust covariance", function_name = "mixed_robust_vcov", status = "implemented"),
  "37" = list(module = "Bootstrap engine", function_name = "mixed_boot", status = "implemented"),
  "38" = list(module = "Fixed-effect bootstrap", function_name = "mixed_boot_fixed", status = "implemented"),
  "39" = list(module = "Variance-component bootstrap", function_name = "mixed_boot_variance", status = "implemented"),
  "40" = list(module = "Prediction bootstrap", function_name = "mixed_boot_predict", status = "implemented"),
  "41" = list(module = "Mixed GAMLSS", function_name = "mixed_gamlss", status = "implemented"),
  "42" = list(module = "GAMLSS parameter extraction", function_name = "mixed_gamlss_parameters", status = "implemented"),
  "43" = list(module = "GAMLSS comparison/selection", function_name = "mixed_gamlss_select", status = "implemented"),
  "44" = list(module = "GAMLSS conditional quantiles", function_name = "mixed_gamlss_quantiles", status = "implemented"),
  "45" = list(module = "GAMLSS diagnostics", function_name = "mixed_gamlss_diagnose", status = "implemented"),
  "46" = list(module = "Bayesian multilevel fit", function_name = "mixed_bayes", status = "implemented"),
  "47" = list(module = "Prior inspection", function_name = "mixed_prior", status = "implemented"),
  "48" = list(module = "Prior predictive analysis", function_name = "mixed_prior_predictive", status = "implemented"),
  "49" = list(module = "Posterior draws", function_name = "mixed_posterior", status = "implemented"),
  "50" = list(module = "Posterior predictive checking", function_name = "mixed_pp_check", status = "implemented"),
  "51" = list(module = "Bayesian predictive comparison", function_name = "mixed_loo", status = "implemented"),
  "52" = list(module = "Estimated marginal means", function_name = "mixed_emmeans", status = "implemented"),
  "53" = list(module = "Contrasts", function_name = "mixed_contrasts", status = "implemented"),
  "54" = list(module = "Compact letter display", function_name = "mixed_cld", status = "implemented"),
  "55" = list(module = "Quantitative trends", function_name = "mixed_trend", status = "implemented"),
  "56" = list(module = "Prediction curves", function_name = "mixed_curve", status = "implemented"),
  "57" = list(module = "Nonlinear mixed model", function_name = "mixed_nonlinear", status = "implemented"),
  "58" = list(module = "Growth curves", function_name = "mixed_growth", status = "implemented"),
  "59" = list(module = "Dose response", function_name = "mixed_dose_response", status = "implemented"),
  "60" = list(module = "Random regression curves", function_name = "mixed_random_curve", status = "implemented"),
  "61" = list(module = "Spatial field trials", function_name = "mixed_spatial_field", status = "implemented"),
  "62" = list(module = "Spatial surface extraction", function_name = "mixed_spatial_surface", status = "implemented"),
  "63" = list(module = "Multi-environment trials", function_name = "mixed_met", status = "implemented"),
  "64" = list(module = "GxE/reduced-rank models", function_name = "mixed_gxe", status = "implemented"),
  "65" = list(module = "Diagnostics", function_name = "mixed_diagnose", status = "implemented"),
  "66" = list(module = "Influence", function_name = "mixed_influence", status = "implemented"),
  "67" = list(module = "Model comparison", function_name = "mixed_compare", status = "implemented"),
  "68" = list(module = "Publication tables", function_name = "mixed_table", status = "implemented"),
  "69" = list(module = "Publication plots", function_name = "mixed_plot", status = "implemented"),
  "70" = list(module = "Guided teaching tour", function_name = "mixed_tour", status = "implemented")
)
